// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo68JQeOyxsLU7BHJByfqWYEzG0tOwTic',
    appId: '1:467951604055:web:f0caecc3d72ff0b1df2e12',
    messagingSenderId: '467951604055',
    projectId: 'project2-restaurantapp',
    authDomain: 'project2-restaurantapp.firebaseapp.com',
    storageBucket: 'project2-restaurantapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGr95W97pSDoqEZTcOsMlOA2EzeBtanEo',
    appId: '1:467951604055:android:cf039f5d7835ddbddf2e12',
    messagingSenderId: '467951604055',
    projectId: 'project2-restaurantapp',
    storageBucket: 'project2-restaurantapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBInqnvhiDTPoPxEzU7Lbvsg8K2XG7XvfI',
    appId: '1:467951604055:ios:10ec73d94d2615abdf2e12',
    messagingSenderId: '467951604055',
    projectId: 'project2-restaurantapp',
    storageBucket: 'project2-restaurantapp.firebasestorage.app',
    iosBundleId: 'com.example.cisProject2ResaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBInqnvhiDTPoPxEzU7Lbvsg8K2XG7XvfI',
    appId: '1:467951604055:ios:10ec73d94d2615abdf2e12',
    messagingSenderId: '467951604055',
    projectId: 'project2-restaurantapp',
    storageBucket: 'project2-restaurantapp.firebasestorage.app',
    iosBundleId: 'com.example.cisProject2ResaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo68JQeOyxsLU7BHJByfqWYEzG0tOwTic',
    appId: '1:467951604055:web:add23d2538ec6ecedf2e12',
    messagingSenderId: '467951604055',
    projectId: 'project2-restaurantapp',
    authDomain: 'project2-restaurantapp.firebaseapp.com',
    storageBucket: 'project2-restaurantapp.firebasestorage.app',
  );
}
